---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Ryan A. Peek

jobtitle: "PhD Candidate, Ecology, UC Davis"
address: "1000 Tulip Lane · Davis · CA 95618"
fontawesome: yes
email: rapeek@ucdavis.edu
github: ryanpeek
#phone: "+353 1 408 4800"
web: ryanpeek.github.io
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Employment

*Center for Watershed Sciences, University of California, Davis*

Graduate Student Researcher \hfill 2014-present

Jr. Research Specialist \hfill 2011-2014

*USDA Forest Service, Pacific Southwest Research Station*

Biological Science Technician \hfill 2010

*University of California, Berkeley*

Research Assistant II  \hfill 2009-2010

*Stillwater Sciences*

Fish & Wildlife Biologist \hfill 8/2002–12/2011

*National Park Service (Sequoia and Kings Canyon)*

Biological Science Technician \hfill 2001  

# Education

*University of California, Davis*, Ph.D. Ecology \hfill expected 2018  
*University of San Francisco*, M.S. Biology \hfill 2010  
*University of California, Davis*, B.S. Wildlife, Fish, & Conservation Biology \hfill 2002  

# Teaching

*Instructor, Software & Data Carpentry* \hfill 2016

> Help teach researchers in science, engineering, medicine, and related disciplines the computing skills they need to get more done using open source and reproducible tools. Specifically, have helped teach ecology/natural science workshops at UC Davis and UC Berkeley. (http://software-carpentry.org/) (http://www.datacarpentry.org/)

*Teaching Assistant, Ecogeomorphology, University of California Davis* \hfill 2015

> Introduced advanced undergraduate students to multidisciplinary collaborative watershed and stream analysis through combined laboratory and field study of a selected stream system. Taught students from diverse backgrounds to work in interdisciplinary research teams to collect and analyze field data from the Tuolumne River system. Guided and taught in classroom, lab, and field, including a 3 day rafting trip on the Tuolumne River.

*Lab Instructor/Teaching Assistant, General Biology, University of San Francisco* \hfill 2009-2010

> Lab instructor for undergraduate general biology lab; planned and conducted lab activities and led discussions for two semesters (molecular biology fall semester, organismal biology spring semester).  Gave weekly lecture to the class. Wrote weekly quizzes, graded students reports and exams

# Publications

## Books

Pearson, E.S. and John Wishart (eds.). 1943. *"Student's" Collected Papers* London: Biometrika Office.

## Journal Articles

Student. 1938. "Comparison between Balanced and Random Arrangements on Field Plots." *Biometrika* 29(3-4): 363--378.

Student. 1936. "Co-operation in Large Scale Experiments." *Supplement to Journal of the Royal Statistical Society* 3(2): 115--136.

Student. 1931. "On the *z* Test." *Biometrika* 23(3-4): 407-408.

Student. 1931. "The Lanarkshire Milk Experiment." *Biometrika* 23(3-4): 398--406.

Student. 1929. "Statistics in Biological Research." *Nature* 124: 93

Student. 1927. "Errors of Routine Analysis." *Biometrika* 19(1-2): 151--164.

Student. 1926. "Mathematics and Agronomy." *Journal of the American Society of Agronomy* 18.

Student. 1925. "New Tables for Testing the Significance of Observations." *Metron* 5(3): 105--108.

Student. 1923. "On Testing Varieties of Cereals." *Biometrika* 15(3-4): 271--293.

Student. 1921. "An Experimental Determination of the Probable Error of Dr. Spearman's Correlation Co-efficient" *Biometrika* 13(2-3): 263--282.

Student. 1917. "Tables for Estimating the Probability That the Given Mean of a Unique Sample of Observations Lies between $-\infty$ and Any Given Distance of the Mean of the Population from Which the Sample Is Drawn." *Biometrika* 11(4): 414--417.

Student. 1909. "The Distribution of the Means of Samples Which Are Not Drawn at Random." *Biometrika* 7(1-2): 210--214.

Student. 1908. "Probable Error of a Correlation Coefficient." *Biometrika* 6(2-3): 302--310.

Student. 1908. "The Probable Error of a Mean." *Biometrika* 6(1): 1--25.

Student. 1907. "On the Error of Counting with a Haemacytometer." *Biometrika* 5(3): 351--360.

## Other Publications

Student. 1905. "The Pearson Co-efficient of Correlation." Supplement to Report of 1904, Arthur Guinness Son & Company.

Student. 1904. "The Application of the 'Law of Error' to the Work of the Brewery." Report, Arthur Guinness Son & Company.

# References

Available upon request